
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pro_petmanage?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
mybatis:
  mapper-locations:
   classpath:mapper/*.xml
server:
  port: 80
